name: Build & Deploy test spring cache app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy test spring cache app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Unit tests
        run: mvn -B test --file pom.xml

      - name: Build application
        run: |
          mvn clean
          mvn -B package --file pom.xml